import Quickshell
import Quickshell.Io
import Quickshell.Hyprland
import QtQuick

Item {
  id: hypr
  property var host

  function utf8Hex(str) {
    const s = unescape(encodeURIComponent(str))
    let hex = ""
    for (let i = 0; i < s.length; i++)
      hex += ("0" + s.charCodeAt(i).toString(16)).slice(-2)
    return hex
  }

  function generalConfText() {
    const c = String(host.accentColor).replace("#", "")
    let out = "# Generated by Proteus Settings — Desktop\n"
    out += "# Edit here or in Settings → Desktop. Applied via hyprctl + reload.\n\n"
    out += "general {\n"
    out += "  gaps_in = " + host.gapsIn + "\n"
    out += "  gaps_out = " + host.gapsOut + "\n"
    out += "  border_size = " + host.borderSize + "\n"
    out += "  col.active_border = rgba(" + c + "cc)\n"
    out += "  col.inactive_border = rgba(2a3544aa)\n"
    out += "}\n\n"
    out += "decoration {\n"
    out += "  host.rounding = " + host.rounding + "\n"
    out += "  blur {\n"
    out += "    enabled = " + (host.chromeBlur ? "true" : "false") + "\n"
    out += "    size = " + (host.chromeBlur ? "10" : "0") + "\n"
    out += "    passes = " + (host.chromeBlur ? "2" : "1") + "\n"
    out += "  }\n"
    out += "}\n\n"
    out += "animations {\n"
    out += "  enabled = " + (host.animationsEnabled ? "true" : "false") + "\n"
    out += "}\n\n"
    out += "input {\n"
    out += "  sensitivity = " + host.mouseSensitivity + "\n"
    out += "  accel_profile = " + (host.mouseAccelFlat ? "flat" : "adaptive") + "\n"
    out += "}\n\n"
    if (host.chromeBlur) {
      out += "# Quickshell chrome blur (Settings → Appearance) — Hyprland ≥0.56\n"
      out += "layerrule = blur on, ignore_alpha 0.2, match:namespace quickshell\n"
    }
    return out
  }

  function applyHyprlandLive() {
    const c = String(host.accentColor).replace("#", "")
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "general:gaps_in", String(host.gapsIn)]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "general:gaps_out", String(host.gapsOut)]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "general:border_size", String(host.borderSize)]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "general:col.active_border", "rgba(" + c + "cc)"]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "decoration:host.rounding", String(host.rounding)]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "animations:enabled", host.animationsEnabled ? "true" : "false"]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "input:sensitivity", String(host.mouseSensitivity)]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "input:accel_profile", host.mouseAccelFlat ? "flat" : "adaptive"]
    })
  }

  function persistGeneralConf() {
    // Debounce so JsonAdapter batch-loads (accent before host.chromeBlur) don't
    // write a half-applied proteus-general.conf.
    persistGeneralTimer.restart()
  }

  function persistGeneralConfNow() {
    const confHex = utf8Hex(generalConfText())
    generalWriteProc.command = ["python3", "-c",
      "import os, pathlib, subprocess\n"
      + "home = pathlib.Path(os.environ['HOME'])\n"
      + "(home / '.config/hypr').mkdir(parents=True, exist_ok=True)\n"
      + "(home / '.config/hypr/proteus-general.conf').write_text(bytes.fromhex('" + confHex + "').decode(), encoding='utf-8')\n"
      + "hypr = home / '.config/hypr/hyprland.conf'\n"
      + "if hypr.is_file():\n"
      + "    text = hypr.read_text(encoding='utf-8')\n"
      + "    if 'proteus-general.conf' not in text:\n"
      + "        hypr.write_text(text.rstrip() + '\\n\\n# Proteus desktop (Settings → Desktop)\\nsource = ~/.config/hypr/proteus-general.conf\\n', encoding='utf-8')\n"
      + "print('ok')\n"
    ]
    generalWriteProc.running = false
    generalWriteProc.running = true
  }

  Timer {
    id: persistGeneralTimer
    interval: 80
    repeat: false
    onTriggered: host.persistGeneralConfNow()
  }

  function applyHyprland() {
    applyHyprlandLive()
    persistGeneralConf()
  }

  function openGeneralConfInEditor() {
    Quickshell.execDetached({
      command: ["bash", "-lc", "mkdir -p \"$HOME/.config/hypr\"; touch \"$HOME/.config/hypr/proteus-general.conf\"; (command -v xdg-open >/dev/null && xdg-open \"$HOME/.config/hypr/proteus-general.conf\") || exec ghostty -e nvim \"$HOME/.config/hypr/proteus-general.conf\""]
    })
  }

  function openSettingsJsonInEditor() {
    Quickshell.execDetached({
      command: [
        "bash",
        "-lc",
        "mkdir -p \"$HOME/.config/proteus\"; touch \"$HOME/.config/proteus/settings.json\"; "
            + "(command -v xdg-open >/dev/null && xdg-open \"$HOME/.config/proteus/settings.json\") "
            + "|| exec ghostty -e nvim \"$HOME/.config/proteus/settings.json\""
      ]
    })
  }

  function setChromeMode(mode) {
    const m = String(mode || "")
    if (m !== "dark" && m !== "light")
      return
    host.chromeMode = m
  }

  function setChromeOpacity(v) {
    const n = Math.max(0, Math.min(1, Math.round(Number(v) * 100) / 100))
    host.chromeOpacity = n
    applyChromeEffects()
  }

  function setChromeBlur(on) {
    host.chromeBlur = !!on
    // Blur needs some see-through; nudge if still fully opaque
    if (host.chromeBlur && host.chromeOpacity > 0.92)
      host.chromeOpacity = 0.78
    applyChromeEffects()
  }

  // Menu bar / dock placement: "all" or an output name from Quickshell.screens.
  function chromeOnScreen(screen, selector) {
    const sel = String(selector || "all").trim()
    if (!sel.length || sel === "all")
      return true
    if (!screen)
      return false
    const screens = Quickshell.screens
    let found = false
    for (let i = 0; i < screens.length; i++) {
      if (String(screens[i].name) === sel) {
        found = true
        break
      }
    }
    if (!found) {
      // Saved output unplugged — keep chrome on the first screen
      return screens.length > 0 && screen === screens[0]
    }
    return String(screen.name) === sel
  }

  function chromeScreenOptions() {
    const out = [
      {
        id: "all",
        label: "All displays"
      }
    ]
    const screens = Quickshell.screens
    for (let i = 0; i < screens.length; i++) {
      const s = screens[i]
      const name = String(s.name || ("Display " + (i + 1)))
      const geo = s.width && s.height ? (" · " + s.width + "×" + s.height) : ""
      out.push({
        id: name,
        label: name + geo
      })
    }
    return out
  }

  function applyChromeEffects() {
    persistGeneralConf()
    const blurOn = host.chromeBlur ? "1" : "0"
    const size = host.chromeBlur ? "10" : "0"
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "decoration:blur:enabled", blurOn]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "decoration:blur:size", size]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "decoration:blur:passes", host.chromeBlur ? "2" : "1"]
    })
    if (host.chromeBlur) {
      // Hyprland ≥0.56 layerrule syntax
      Quickshell.execDetached({
        command: ["hyprctl", "keyword", "layerrule", "blur on, ignore_alpha 0.2, match:namespace quickshell"]
      })
    }
    Quickshell.execDetached({
      command: ["hyprctl", "reload"]
    })
  }
  Process {
    id: generalWriteProc
    command: ["true"]
  }
}
