import Quickshell
import Quickshell.Io
import Quickshell.Hyprland
import QtQuick

Item {
  id: hypr
  property var host

  function utf8Hex(str) {
    const s = unescape(encodeURIComponent(str))
    let hex = ""
    for (let i = 0; i < s.length; i++)
      hex += ("0" + s.charCodeAt(i).toString(16)).slice(-2)
    return hex
  }

  function generalConfText() {
    const c = String(host.accentColor).replace("#", "")
    const blurOn = !!host.chromeBlur
    const opacity = Math.max(0, Math.min(1, Number(host.chromeOpacity) || 1))
    // Stronger frost when see-through; dock shelf wants continuous glass body
    const blurSize = blurOn ? Math.round(8 + (1 - opacity) * 12) : 0
    const blurPasses = blurOn ? (opacity < 0.55 ? 3 : 2) : 1
    // Let frosted pixels sample the backdrop (Hypr ≥0.56)
    const ignoreAlpha = "0.08"
    let out = "# Generated by Proteus Settings — Desktop\n"
    out += "# Edit here or in Settings → Desktop. Applied via hyprctl + reload.\n\n"
    out += "general {\n"
    out += "  gaps_in = " + host.gapsIn + "\n"
    out += "  gaps_out = " + host.gapsOut + "\n"
    out += "  border_size = " + host.borderSize + "\n"
    out += "  col.active_border = rgba(" + c + "cc)\n"
    out += "  col.inactive_border = rgba(2a3544aa)\n"
    out += "}\n\n"
    out += "decoration {\n"
    out += "  rounding = " + host.rounding + "\n"
    out += "  blur {\n"
    out += "    enabled = " + (blurOn ? "true" : "false") + "\n"
    out += "    size = " + blurSize + "\n"
    out += "    passes = " + blurPasses + "\n"
    out += "    ignore_opacity = true\n"
    out += "    xray = false\n"
    out += "  }\n"
    out += "}\n\n"
    out += "animations {\n"
    out += "  enabled = " + (host.animationsEnabled ? "true" : "false") + "\n"
    out += "}\n\n"
    out += "input {\n"
    out += "  sensitivity = " + host.mouseSensitivity + "\n"
    out += "  accel_profile = " + (host.mouseAccelFlat ? "flat" : "adaptive") + "\n"
    out += "}\n\n"
    if (blurOn) {
      out += "# Proteus chrome blur (Settings → Appearance) — Hyprland ≥0.56\n"
      out += "# Scope to chrome namespaces only (not wallpaper / desktop widgets).\n"
      const namespaces = ["proteus-bar", "proteus-dock", "proteus-launcher", "proteus-control-center", "proteus-hud"]
      for (let i = 0; i < namespaces.length; i++)
        out += "layerrule = blur on, ignore_alpha " + ignoreAlpha + ", match:namespace " + namespaces[i] + "\n"
    }
    return out
  }

  function applyHyprlandLive() {
    const c = String(host.accentColor).replace("#", "")
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "general:gaps_in", String(host.gapsIn)]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "general:gaps_out", String(host.gapsOut)]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "general:border_size", String(host.borderSize)]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "general:col.active_border", "rgba(" + c + "cc)"]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "decoration:rounding", String(host.rounding)]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "animations:enabled", host.animationsEnabled ? "true" : "false"]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "input:sensitivity", String(host.mouseSensitivity)]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "input:accel_profile", host.mouseAccelFlat ? "flat" : "adaptive"]
    })
  }

  function persistGeneralConf() {
    // Debounce so JsonAdapter batch-loads (accent before host.chromeBlur) don't
    // write a half-applied proteus-general.conf.
    persistGeneralTimer.restart()
  }

  function persistGeneralConfNow() {
    const confHex = utf8Hex(generalConfText())
    generalWriteProc.command = ["python3", "-c",
      "import os, pathlib, subprocess\n"
      + "home = pathlib.Path(os.environ['HOME'])\n"
      + "(home / '.config/hypr').mkdir(parents=True, exist_ok=True)\n"
      + "(home / '.config/hypr/proteus-general.conf').write_text(bytes.fromhex('" + confHex + "').decode(), encoding='utf-8')\n"
      + "hypr = home / '.config/hypr/hyprland.conf'\n"
      + "if hypr.is_file():\n"
      + "    text = hypr.read_text(encoding='utf-8')\n"
      + "    if 'proteus-general.conf' not in text:\n"
      + "        hypr.write_text(text.rstrip() + '\\n\\n# Proteus desktop (Settings → Desktop)\\nsource = ~/.config/hypr/proteus-general.conf\\n', encoding='utf-8')\n"
      + "print('ok')\n"
    ]
    generalWriteProc.running = false
    generalWriteProc.running = true
  }

  Timer {
    id: persistGeneralTimer
    interval: 80
    repeat: false
    onTriggered: host.persistGeneralConfNow()
  }

  // Accent/color graph drags used to spam hyprctl every mouse tick.
  Timer {
    id: applyHyprLiveTimer
    interval: 60
    repeat: false
    onTriggered: applyHyprlandLive()
  }

  function applyHyprland() {
    applyHyprLiveTimer.restart()
    persistGeneralConf()
  }

  function openGeneralConfInEditor() {
    Quickshell.execDetached({
      command: ["bash", "-lc", "mkdir -p \"$HOME/.config/hypr\"; touch \"$HOME/.config/hypr/proteus-general.conf\"; (command -v xdg-open >/dev/null && xdg-open \"$HOME/.config/hypr/proteus-general.conf\") || exec proteus-terminal -e nvim \"$HOME/.config/hypr/proteus-general.conf\""]
    })
  }

  function openSettingsJsonInEditor() {
    Quickshell.execDetached({
      command: [
        "bash",
        "-lc",
        "mkdir -p \"$HOME/.config/proteus\"; touch \"$HOME/.config/proteus/settings.json\"; "
            + "(command -v xdg-open >/dev/null && xdg-open \"$HOME/.config/proteus/settings.json\") "
            + "|| exec proteus-terminal -e nvim \"$HOME/.config/proteus/settings.json\""
      ]
    })
  }

  function setChromeMode(mode) {
    const m = String(mode || "")
    if (m !== "dark" && m !== "light")
      return
    host.chromeMode = m
  }

  function setChromeOpacity(v) {
    const n = Math.max(0, Math.min(1, Math.round(Number(v) * 100) / 100))
    host.chromeOpacity = n
    // Opacity is live via Theme — only retune Hypr blur when frosted glass is on.
    // Never full-reload on every slider tick (that caused jank / ghosting).
    if (host.chromeBlur)
      chromeBlurTuneTimer.restart()
  }

  function setChromeBlur(on) {
    const want = !!on
    host.chromeBlur = want
    // Blur needs see-through; ease opaque chrome down gently
    if (want && host.chromeOpacity > 0.92)
      host.chromeOpacity = 0.72
    // Layerrules must be rewritten — debounce then reload once
    chromeBlurApplyTimer.restart()
  }

  Timer {
    id: chromeBlurTuneTimer
    interval: 140
    repeat: false
    onTriggered: applyChromeBlurLive(false)
  }

  Timer {
    id: chromeBlurApplyTimer
    interval: 100
    repeat: false
    onTriggered: applyChromeBlurLive(true)
  }

  function chromeBlurParams() {
    const opacity = Math.max(0, Math.min(1, Number(host.chromeOpacity) || 1))
    const blurOn = !!host.chromeBlur
    return {
      enabled: blurOn,
      size: blurOn ? Math.round(6 + (1 - opacity) * 10) : 0,
      passes: blurOn ? (opacity < 0.45 ? 3 : 2) : 1,
      ignoreAlpha: "0.05"
    }
  }

  // reload=true when enabling/disabling blur (layerrules in conf must replace).
  // reload=false for opacity drags — keyword-tune size/passes only.
  function applyChromeBlurLive(reload) {
    persistGeneralConf()
    const p = chromeBlurParams()
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "decoration:blur:enabled", p.enabled ? "1" : "0"]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "decoration:blur:size", String(p.size)]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "decoration:blur:passes", String(p.passes)]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "decoration:blur:ignore_opacity", "1"]
    })
    if (p.enabled) {
      const namespaces = ["proteus-bar", "proteus-dock", "proteus-launcher", "proteus-control-center", "proteus-hud"]
      for (let i = 0; i < namespaces.length; i++) {
        Quickshell.execDetached({
          command: ["hyprctl", "keyword", "layerrule", "blur on, ignore_alpha " + p.ignoreAlpha + ", match:namespace " + namespaces[i]]
        })
      }
    }
    if (reload) {
      // Persist conf (clears layerrules when blur off), then reload once
      persistGeneralConf()
      chromeReloadTimer.restart()
    }
  }

  Timer {
    id: chromeReloadTimer
    interval: 160
    repeat: false
    onTriggered: Quickshell.execDetached({
      command: ["hyprctl", "reload"]
    })
  }

  function applyChromeEffects() {
    // Back-compat entry — full apply with reload
    applyChromeBlurLive(true)
  }

  // Menu bar / dock placement: "all" or an output name from Quickshell.screens.
  function chromeOnScreen(screen, selector) {
    const sel = String(selector || "all").trim()
    if (!sel.length || sel === "all")
      return true
    if (!screen)
      return false
    const screens = Quickshell.screens
    let found = false
    for (let i = 0; i < screens.length; i++) {
      if (String(screens[i].name) === sel) {
        found = true
        break
      }
    }
    if (!found) {
      // Saved output unplugged — keep chrome on the first screen
      return screens.length > 0 && screen === screens[0]
    }
    return String(screen.name) === sel
  }

  function chromeScreenOptions() {
    const out = [
      {
        id: "all",
        label: "All displays"
      }
    ]
    const screens = Quickshell.screens
    for (let i = 0; i < screens.length; i++) {
      const s = screens[i]
      const name = String(s.name || ("Display " + (i + 1)))
      const geo = s.width && s.height ? (" · " + s.width + "×" + s.height) : ""
      out.push({
        id: name,
        label: name + geo
      })
    }
    return out
  }

  Process {
    id: generalWriteProc
    command: ["true"]
  }
}
