pragma Singleton

import Quickshell
import Quickshell.Io
import Quickshell.Hyprland
import QtQuick

Singleton {
  id: root

  property alias gapsIn: adapter.gapsIn
  property alias gapsOut: adapter.gapsOut
  property alias borderSize: adapter.borderSize
  property alias rounding: adapter.rounding
  property alias animationsEnabled: adapter.animationsEnabled
  property alias dockEnabled: adapter.dockEnabled
  property alias mouseSensitivity: adapter.mouseSensitivity
  property alias mouseAccelFlat: adapter.mouseAccelFlat
  property alias audioLatency: adapter.audioLatency
  property alias accentId: adapter.accentId
  property alias wallpaperId: adapter.wallpaperId
  property alias wallpaperMode: adapter.wallpaperMode
  property alias fontFamily: adapter.fontFamily
  property alias fontSize: adapter.fontSize
  property alias fontSizeSm: adapter.fontSizeSm

  // PipeWire clock.force-quantum profiles (frames @ graph rate, usually 48 kHz).
  readonly property var audioLatencyProfiles: [
    {
      id: "low",
      label: "Low",
      hint: "~5 ms · snappier, may crackle",
      quantum: 256
    },
    {
      id: "balanced",
      label: "Balanced",
      hint: "~11 ms · general use",
      quantum: 512
    },
    {
      id: "high",
      label: "High",
      hint: "~21 ms · smoother playback",
      quantum: 1024
    }
  ]

  // Packages hub badge (−1 = not checked yet)
  property int packageUpgradeCount: -1

  // Privileged mutator (services/proteus-pkg via pkexec)
  property bool packageOpBusy: false
  property string packageOpStatus: ""
  property string packageBinPath: ""

  signal packageOpFinished(bool ok, string message)

  function notePackageUpgrades(count) {
    packageUpgradeCount = count
  }

  function shellQuote(s) {
    return "'" + String(s).replace(/'/g, "'\\''") + "'"
  }

  readonly property var repoPkgCandidates: {
    const shell = Quickshell.shellRoot
    const bases = []
    if (shell && shell.length) {
      bases.push(shell + "/../../services/proteus-pkg")
      bases.push(shell + "/../services/proteus-pkg")
    }
    bases.push("/mnt/proteus/services/proteus-pkg")
    return bases
  }

  readonly property string generalConfPath: Quickshell.env("HOME") + "/.config/hypr/proteus-general.conf"
  readonly property string monitorsConfPath: Quickshell.env("HOME") + "/.config/hypr/proteus-monitors.conf"

  readonly property var fonts: [
    {
      id: "Sans",
      label: "Sans"
    },
    {
      id: "Noto Sans",
      label: "Noto Sans"
    },
    {
      id: "DejaVu Sans",
      label: "DejaVu"
    },
    {
      id: "Cantarell",
      label: "Cantarell"
    },
    {
      id: "JetBrains Mono",
      label: "JetBrains Mono"
    },
    {
      id: "monospace",
      label: "Monospace"
    }
  ]

  readonly property string assetsDir: {
    const root = Quickshell.shellRoot
    return (root && root.length ? root : "/mnt/proteus/shell") + "/assets"
  }

  readonly property var wallpapers: [
    {
      id: "default",
      label: "Default",
      path: assetsDir + "/wallpaper.png"
    },
    {
      id: "dusk",
      label: "Dusk",
      path: assetsDir + "/wallpaper-dusk.png"
    },
    {
      id: "tide",
      label: "Tide",
      path: assetsDir + "/wallpaper-tide.png"
    },
    {
      id: "violet",
      label: "Violet",
      path: assetsDir + "/wallpaper-violet.png"
    }
  ]

  readonly property string wallpaperPath: {
    for (let i = 0; i < wallpapers.length; i++) {
      if (wallpapers[i].id === wallpaperId)
        return wallpapers[i].path
    }
    return wallpapers[0].path
  }

  readonly property var accents: [
    {
      id: "blue",
      label: "Electric",
      color: "#3d8bfd"
    },
    {
      id: "teal",
      label: "Teal",
      color: "#2dd4bf"
    },
    {
      id: "violet",
      label: "Violet",
      color: "#a78bfa"
    },
    {
      id: "amber",
      label: "Amber",
      color: "#fbbf24"
    },
    {
      id: "rose",
      label: "Rose",
      color: "#fb7185"
    }
  ]

  readonly property color accentColor: {
    for (let i = 0; i < accents.length; i++) {
      if (accents[i].id === accentId)
        return accents[i].color
    }
    return accents[0].color
  }

  function utf8Hex(str) {
    const s = unescape(encodeURIComponent(str))
    let hex = ""
    for (let i = 0; i < s.length; i++)
      hex += ("0" + s.charCodeAt(i).toString(16)).slice(-2)
    return hex
  }

  function generalConfText() {
    const c = String(accentColor).replace("#", "")
    let out = "# Generated by Proteus Settings — Desktop\n"
    out += "# Edit here or in Settings → Desktop. Applied via hyprctl + reload.\n\n"
    out += "general {\n"
    out += "  gaps_in = " + gapsIn + "\n"
    out += "  gaps_out = " + gapsOut + "\n"
    out += "  border_size = " + borderSize + "\n"
    out += "  col.active_border = rgba(" + c + "cc)\n"
    out += "  col.inactive_border = rgba(2a3544aa)\n"
    out += "}\n\n"
    out += "decoration {\n"
    out += "  rounding = " + rounding + "\n"
    out += "}\n\n"
    out += "animations {\n"
    out += "  enabled = " + (animationsEnabled ? "true" : "false") + "\n"
    out += "}\n\n"
    out += "input {\n"
    out += "  sensitivity = " + mouseSensitivity + "\n"
    out += "  accel_profile = " + (mouseAccelFlat ? "flat" : "adaptive") + "\n"
    out += "}\n"
    return out
  }

  function applyHyprlandLive() {
    const c = String(accentColor).replace("#", "")
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "general:gaps_in", String(gapsIn)]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "general:gaps_out", String(gapsOut)]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "general:border_size", String(borderSize)]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "general:col.active_border", "rgba(" + c + "cc)"]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "decoration:rounding", String(rounding)]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "animations:enabled", animationsEnabled ? "true" : "false"]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "input:sensitivity", String(mouseSensitivity)]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "input:accel_profile", mouseAccelFlat ? "flat" : "adaptive"]
    })
  }

  function persistGeneralConf() {
    const confHex = utf8Hex(generalConfText())
    generalWriteProc.command = ["python3", "-c",
      "import os, pathlib, subprocess\n"
      + "home = pathlib.Path(os.environ['HOME'])\n"
      + "(home / '.config/hypr').mkdir(parents=True, exist_ok=True)\n"
      + "(home / '.config/hypr/proteus-general.conf').write_text(bytes.fromhex('" + confHex + "').decode(), encoding='utf-8')\n"
      + "hypr = home / '.config/hypr/hyprland.conf'\n"
      + "if hypr.is_file():\n"
      + "    text = hypr.read_text(encoding='utf-8')\n"
      + "    if 'proteus-general.conf' not in text:\n"
      + "        hypr.write_text(text.rstrip() + '\\n\\n# Proteus desktop (Settings → Desktop)\\nsource = ~/.config/hypr/proteus-general.conf\\n', encoding='utf-8')\n"
      + "print('ok')\n"
    ]
    generalWriteProc.running = false
    generalWriteProc.running = true
  }

  function applyHyprland() {
    applyHyprlandLive()
    persistGeneralConf()
  }

  function openGeneralConfInEditor() {
    Quickshell.execDetached({
      command: ["bash", "-lc", "mkdir -p \"$HOME/.config/hypr\"; touch \"$HOME/.config/hypr/proteus-general.conf\"; (command -v xdg-open >/dev/null && xdg-open \"$HOME/.config/hypr/proteus-general.conf\") || exec foot -e nvim \"$HOME/.config/hypr/proteus-general.conf\""]
    })
  }

  function openMonitorsConfInEditor() {
    Quickshell.execDetached({
      command: ["bash", "-lc", "mkdir -p \"$HOME/.config/hypr\"; touch \"$HOME/.config/hypr/proteus-monitors.conf\"; (command -v xdg-open >/dev/null && xdg-open \"$HOME/.config/hypr/proteus-monitors.conf\") || exec foot -e nvim \"$HOME/.config/hypr/proteus-monitors.conf\""]
    })
  }

  function monitorRule(m) {
    const name = m.name || "?"
    const w = Math.round(m.width || 1920)
    const h = Math.round(m.height || 1080)
    const hz = Math.round(m.refreshRate || m.refresh || 60)
    const x = Math.round(m.x || 0)
    const y = Math.round(m.y || 0)
    const scale = Number(m.scale)
    const scaleStr = isFinite(scale) && scale > 0 ? String(Math.round(scale * 100) / 100) : "1"
    let t = Math.round(Number(m.transform))
    if (!isFinite(t) || t < 0)
      t = 0
    t = t % 8
    // Always emit transform so re-apply is deterministic
    return name + "," + w + "x" + h + "@" + hz + "," + x + "x" + y + "," + scaleStr + ",transform," + t
  }

  function monitorsConfText(monitors, live) {
    let body = "# Generated by Proteus Settings — Displays\n"
    if (live) {
      body += "# Applied from Settings → Displays (scale / mode / orientation). Edit here or re-apply in Settings.\n"
    } else {
      body += "# Inspect / edit manually. Apply in Settings → Displays to write live monitor lines.\n"
    }
    body += "# Sourced by Hyprland when present in hyprland.conf.\n\n"
    const list = monitors || []
    for (let i = 0; i < list.length; i++) {
      const m = list[i]
      const name = m.name || "?"
      body += "# " + name + (m.focused ? " (active)" : "") + "\n"
      const rule = monitorRule(m)
      if (live)
        body += "monitor = " + rule + "\n\n"
      else
        body += "# monitor = " + rule + "\n\n"
    }
    if (!list.length)
      body += "# No monitors detected yet.\n# monitor = ,preferred,auto,1\n"
    return body
  }

  function _writeMonitorsConf(body) {
    const confHex = utf8Hex(body)
    monitorsWriteProc.command = ["python3", "-c",
      "import os, pathlib\n"
      + "home = pathlib.Path(os.environ['HOME'])\n"
      + "(home / '.config/hypr').mkdir(parents=True, exist_ok=True)\n"
      + "path = home / '.config/hypr/proteus-monitors.conf'\n"
      + "new = bytes.fromhex('" + confHex + "').decode()\n"
      + "marker = '# Generated by Proteus Settings — Displays'\n"
      + "existing = path.read_text(encoding='utf-8') if path.is_file() else ''\n"
      + "if (not path.is_file()) or (len(existing.strip()) == 0) or existing.startswith(marker):\n"
      + "    path.write_text(new, encoding='utf-8')\n"
      + "hypr = home / '.config/hypr/hyprland.conf'\n"
      + "if hypr.is_file():\n"
      + "    text = hypr.read_text(encoding='utf-8')\n"
      + "    if 'proteus-monitors.conf' not in text:\n"
      + "        hypr.write_text(text.rstrip() + '\\n\\n# Proteus displays (Settings → Displays)\\nsource = ~/.config/hypr/proteus-monitors.conf\\n', encoding='utf-8')\n"
      + "print('ok')\n"
    ]
    monitorsWriteProc.running = false
    monitorsWriteProc.running = true
  }

  // First-run seed only — never overwrite an existing Proteus-managed conf on refresh.
  function ensureMonitorsConfStub(monitors) {
    const list = monitors || []
    const body = monitorsConfText(list, false)
    const confHex = utf8Hex(body)
    monitorsWriteProc.command = ["python3", "-c",
      "import os, pathlib\n"
      + "home = pathlib.Path(os.environ['HOME'])\n"
      + "(home / '.config/hypr').mkdir(parents=True, exist_ok=True)\n"
      + "path = home / '.config/hypr/proteus-monitors.conf'\n"
      + "new = bytes.fromhex('" + confHex + "').decode()\n"
      + "if not path.is_file():\n"
      + "    path.write_text(new, encoding='utf-8')\n"
      + "hypr = home / '.config/hypr/hyprland.conf'\n"
      + "if hypr.is_file():\n"
      + "    text = hypr.read_text(encoding='utf-8')\n"
      + "    if 'proteus-monitors.conf' not in text:\n"
      + "        hypr.write_text(text.rstrip() + '\\n\\n# Proteus displays (Settings → Displays)\\nsource = ~/.config/hypr/proteus-monitors.conf\\n', encoding='utf-8')\n"
      + "print('ok')\n"
    ]
    monitorsWriteProc.running = false
    monitorsWriteProc.running = true
  }

  function persistMonitorsConf(monitors) {
    _writeMonitorsConf(monitorsConfText(monitors || [], true))
  }

  // Live apply one monitor; `allMonitors` is the full set to persist (with this monitor updated).
  function applyMonitor(spec, allMonitors) {
    if (!spec || !spec.name)
      return
    applyMonitorRule(monitorRule(spec), allMonitors)
  }

  function applyMonitorRule(rule, allMonitors) {
    if (!rule || !String(rule).length)
      return
    // execDetached is more reliable from Settings than a reused Singleton Process
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "monitor", String(rule)]
    })
    if (allMonitors && allMonitors.length)
      persistMonitorsConf(allMonitors)
  }

  // Identify flash target (PanelWindow in Settings shell.qml)
  property string identifyTarget: ""
  property bool identifyActive: false

  function identifyMonitor(name) {
    if (!name || !String(name).length)
      return
    const n = String(name)
    identifyTarget = n
    identifyActive = false
    identifyActive = true
    identifyClearTimer.restart()
    Quickshell.execDetached({
      command: ["hyprctl", "dispatch", "focusmonitor", n]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "notify", "1", "1800", "0", "Monitor: " + n]
    })
  }

  Timer {
    id: identifyClearTimer
    interval: 1700
    repeat: false
    onTriggered: {
      root.identifyActive = false
      root.identifyTarget = ""
    }
  }

  function setVolume(pct) {
    const v = Math.max(0, Math.min(150, Math.round(pct)))
    Quickshell.execDetached({
      command: ["pactl", "set-sink-volume", "@DEFAULT_SINK@", v + "%"]
    })
  }

  function getVolume(callback) {
    volumeProc.callback = callback
    volumeProc.running = false
    volumeProc.running = true
  }

  function setMute(muted) {
    Quickshell.execDetached({
      command: ["pactl", "set-sink-mute", "@DEFAULT_SINK@", muted ? "1" : "0"]
    })
  }

  function getMute(callback) {
    muteProc.callback = callback
    muteProc.running = false
    muteProc.running = true
  }

  function listSinks(callback) {
    sinksProc.callback = callback
    // Resolve default sink name, then list
    defaultSinkProc.callback = name => {
      sinksProc.defaultName = name || ""
      sinksProc.running = false
      sinksProc.running = true
    }
    defaultSinkProc.running = false
    defaultSinkProc.running = true
  }

  function setDefaultSink(nameOrId) {
    if (!nameOrId || !String(nameOrId).length)
      return
    Quickshell.execDetached({
      command: ["pactl", "set-default-sink", String(nameOrId)]
    })
  }

  function formatAudioDeviceName(name) {
    if (!name || !String(name).length)
      return "Unknown"
    const n = String(name)
    if (n.indexOf("null") >= 0)
      return "Null (dummy)"
    if (n.indexOf(".monitor") >= 0)
      return "Monitor"
    const tail = n.split(".").pop() || n
    return tail.replace(/-/g, " ").replace(/\b\w/g, c => c.toUpperCase())
  }

  function playTestSound() {
    Quickshell.execDetached({
      command: [
        "bash",
        "-lc",
        "if command -v paplay >/dev/null; then "
            + "for f in /usr/share/sounds/freedesktop/stereo/bell.oga "
            + "/usr/share/sounds/freedesktop/stereo/complete.oga; do "
            + "[ -f \"$f\" ] && paplay \"$f\" && exit 0; done; fi; "
            + "if command -v speaker-test >/dev/null; then "
            + "timeout 1 speaker-test -t sine -f 880 -l 1 -c 2 >/dev/null; fi"
      ]
    })
  }

  function setSourceVolume(pct) {
    const v = Math.max(0, Math.min(150, Math.round(pct)))
    Quickshell.execDetached({
      command: ["pactl", "set-source-volume", "@DEFAULT_SOURCE@", v + "%"]
    })
  }

  function getSourceVolume(callback) {
    sourceVolumeProc.callback = callback
    sourceVolumeProc.running = false
    sourceVolumeProc.running = true
  }

  function setSourceMute(muted) {
    Quickshell.execDetached({
      command: ["pactl", "set-source-mute", "@DEFAULT_SOURCE@", muted ? "1" : "0"]
    })
  }

  function getSourceMute(callback) {
    sourceMuteProc.callback = callback
    sourceMuteProc.running = false
    sourceMuteProc.running = true
  }

  function listSources(callback) {
    sourcesProc.callback = callback
    defaultSourceProc.callback = name => {
      sourcesProc.defaultName = name || ""
      sourcesProc.running = false
      sourcesProc.running = true
    }
    defaultSourceProc.running = false
    defaultSourceProc.running = true
  }

  function setDefaultSource(nameOrId) {
    if (!nameOrId || !String(nameOrId).length)
      return
    Quickshell.execDetached({
      command: ["pactl", "set-default-source", String(nameOrId)]
    })
  }

  function audioLatencyQuantum(id) {
    const key = id && String(id).length ? String(id) : audioLatency
    for (let i = 0; i < audioLatencyProfiles.length; i++) {
      if (audioLatencyProfiles[i].id === key)
        return audioLatencyProfiles[i].quantum
    }
    return 0
  }

  function setAudioLatency(id) {
    const key = String(id || "")
    let ok = false
    for (let i = 0; i < audioLatencyProfiles.length; i++) {
      if (audioLatencyProfiles[i].id === key) {
        ok = true
        break
      }
    }
    if (!ok)
      return
    audioLatency = key
    applyAudioLatency()
  }

  // Maps Settings preference → PipeWire settings metadata clock.force-quantum.
  // 0 clears the force (PipeWire negotiates from defaults / min-quantum).
  function applyAudioLatency() {
    const q = audioLatencyQuantum(audioLatency)
    Quickshell.execDetached({
      command: ["pw-metadata", "-n", "settings", "0", "clock.force-quantum", String(q > 0 ? q : 0)]
    })
  }

  function getPipeWireClock(callback) {
    pipewireClockProc.callback = callback
    pipewireClockProc.running = false
    pipewireClockProc.running = true
  }

  function session(action) {
    switch (action) {
    case "logout":
      Hyprland.dispatch("exit")
      break
    case "reboot":
      Quickshell.execDetached({
        command: ["systemctl", "reboot"]
      })
      break
    case "shutdown":
      Quickshell.execDetached({
        command: ["systemctl", "poweroff"]
      })
      break
    case "lock":
      Quickshell.execDetached({
        command: ["loginctl", "lock-session"]
      })
      break
    }
  }

  function openNetworkEditor() {
    const nmtui = DesktopEntries.heuristicLookup("nm-connection-editor")
    if (nmtui) {
      nmtui.execute()
      return
    }
    Quickshell.execDetached({
      command: ["foot", "-e", "nmtui"]
    })
  }

  // Escape hatch: real terminal + sudo (when mutator missing / user prefers).
  function openPacmanTerminal(args) {
    const cmd = (args && args.length) ? args.join(" ") : "sudo pacman -Syu"
    Quickshell.execDetached({
      command: [
        "bash",
        "-lc",
        "exec foot -e bash -lc " + JSON.stringify(cmd + '; echo; read -r -p \"Press Enter to close…\" _')
      ]
    })
  }

  function openPacmanUpgrade() {
    runPacmanMutator("upgrade")
  }

  function openPacmanSync() {
    runPacmanMutator("sync")
  }

  function openPacmanInstall(pkg) {
    if (!pkg || !String(pkg).length)
      return
    const name = String(pkg).replace(/[^a-zA-Z0-9@.+_-]/g, "")
    if (!name.length)
      return
    runPacmanMutator("install", name)
  }

  function runPacmanMutator(action, pkg) {
    if (packageOpBusy)
      return
    if (action !== "sync" && action !== "upgrade" && action !== "install")
      return
    if (action === "install" && (!pkg || !String(pkg).length))
      return

    packageOpBusy = true
    packageOpStatus = "Looking up proteus-pkg…"
    pkgPendingAction = action
    pkgPendingPkg = pkg ? String(pkg) : ""

    let script = "BIN=\"\"; "
        + "if [ -x /usr/local/libexec/proteus-pkg ]; then BIN=/usr/local/libexec/proteus-pkg; "
        + "elif command -v proteus-pkg >/dev/null 2>&1; then BIN=$(command -v proteus-pkg); fi; "
    const bases = repoPkgCandidates
    for (let i = 0; i < bases.length; i++) {
      const b = shellQuote(bases[i])
      script += "if [ -z \"$BIN\" ]; then "
          + "for t in target/release/proteus-pkg target/debug/proteus-pkg proteus-pkg; do "
          + "c=" + b + "/$t; if [ -x \"$c\" ]; then BIN=$c; break; fi; done; fi; "
    }
    script += "printf '%s' \"$BIN\""

    pkgResolveProc.command = ["bash", "-c", script]
    pkgResolveProc.running = false
    pkgResolveProc.running = true
  }

  property string pkgPendingAction: ""
  property string pkgPendingPkg: ""

  function _startPkgMutator(bin) {
    packageBinPath = bin
    packageOpStatus = "Authenticate to apply…"
    const args = ["pkexec", bin, pkgPendingAction]
    if (pkgPendingAction === "install")
      args.push(pkgPendingPkg)
    pkgMutatorProc.command = args
    pkgMutatorProc.running = false
    pkgMutatorProc.running = true
  }

  function _finishPkgMutator(ok, message) {
    const action = pkgPendingAction
    packageOpBusy = false
    packageOpStatus = message
    pkgPendingAction = ""
    pkgPendingPkg = ""
    if (ok && (action === "upgrade" || action === "sync" || action === "install"))
      notePackageUpgrades(-1)
    packageOpFinished(ok, message)
  }

  function setWallpaper(id) {
    wallpaperId = id
    applyWallpaper()
  }

  function setWallpaperMode(mode) {
    wallpaperMode = mode
    applyWallpaper()
  }

  function applyWallpaper() {
    const img = JSON.stringify(wallpaperPath)
    const mode = JSON.stringify(wallpaperMode)
    Quickshell.execDetached({
      command: [
        "bash",
        "-lc",
        "pkill -x swaybg 2>/dev/null || true; "
            + "for i in 1 2 3 4 5 6 7 8 9 10; do pgrep -x swaybg >/dev/null || break; sleep 0.05; done; "
            + "exec swaybg -i " + img + " -m " + mode
      ]
    })
  }

  FileView {
    id: configFile
    path: Quickshell.env("HOME") + "/.config/proteus/settings.json"
    watchChanges: true
    onFileChanged: reload()
    onAdapterUpdated: writeAdapter()
    onLoadFailed: error => {
      writeAdapter()
    }

    JsonAdapter {
      id: adapter
      property int gapsIn: 8
      property int gapsOut: 14
      property int borderSize: 2
      property int rounding: 10
      property bool animationsEnabled: true
      property bool dockEnabled: true
      property real mouseSensitivity: 0
      property bool mouseAccelFlat: false
      // low | balanced | high → PipeWire clock.force-quantum 256 / 512 / 1024
      property string audioLatency: "high"
      property string accentId: "blue"
      property string wallpaperId: "default"
      property string wallpaperMode: "fill"
      property string fontFamily: "Sans"
      property int fontSize: 13
      property int fontSizeSm: 12

      onGapsInChanged: root.applyHyprland()
      onGapsOutChanged: root.applyHyprland()
      onBorderSizeChanged: root.applyHyprland()
      onRoundingChanged: root.applyHyprland()
      onAnimationsEnabledChanged: root.applyHyprland()
      onMouseSensitivityChanged: root.applyHyprland()
      onMouseAccelFlatChanged: root.applyHyprland()
      onAccentIdChanged: root.applyHyprland()
      onAudioLatencyChanged: root.applyAudioLatency()
    }
  }

  Process {
    id: volumeProc
    property var callback
    command: ["pactl", "get-sink-volume", "@DEFAULT_SINK@"]
    stdout: StdioCollector {
      onStreamFinished: {
        const m = text.match(/(\d+)%/)
        if (volumeProc.callback)
          volumeProc.callback(m ? parseInt(m[1], 10) : 50)
      }
    }
  }

  Process {
    id: muteProc
    property var callback
    command: ["pactl", "get-sink-mute", "@DEFAULT_SINK@"]
    stdout: StdioCollector {
      onStreamFinished: {
        const muted = /yes/i.test(text)
        if (muteProc.callback)
          muteProc.callback(muted)
      }
    }
  }

  Process {
    id: defaultSinkProc
    property var callback
    command: ["pactl", "get-default-sink"]
    stdout: StdioCollector {
      onStreamFinished: {
        if (defaultSinkProc.callback)
          defaultSinkProc.callback(text.trim())
      }
    }
  }

  Process {
    id: sinksProc
    property var callback
    property string defaultName: ""
    command: ["pactl", "list", "short", "sinks"]
    stdout: StdioCollector {
      onStreamFinished: {
        const def = sinksProc.defaultName
        const lines = text.trim().split("\n").filter(l => l.length)
        const out = []
        for (let i = 0; i < lines.length; i++) {
          // id \t name \t module \t sample \t state
          const parts = lines[i].split("\t")
          if (parts.length < 2)
            continue
          const name = parts[1]
          out.push({
            id: parts[0],
            name: name,
            label: root.formatAudioDeviceName(name),
            driver: parts[2] || "",
            sample: parts[3] || "",
            state: parts[4] || "",
            isDefault: name === def
          })
        }
        if (sinksProc.callback)
          sinksProc.callback(out)
      }
    }
  }

  Process {
    id: pipewireClockProc
    property var callback
    command: ["pw-metadata", "-n", "settings", "0"]
    stdout: StdioCollector {
      onStreamFinished: {
        const rateM = text.match(/key:'clock\.rate'\s+value:'(\d+)'/)
        const forceM = text.match(/key:'clock\.force-quantum'\s+value:'(\d+)'/)
        const quantumM = text.match(/key:'clock\.quantum'\s+value:'(\d+)'/)
        if (pipewireClockProc.callback) {
          pipewireClockProc.callback({
            rate: rateM ? parseInt(rateM[1], 10) : 0,
            forceQuantum: forceM ? parseInt(forceM[1], 10) : 0,
            quantum: quantumM ? parseInt(quantumM[1], 10) : 0
          })
        }
      }
    }
  }

  Process {
    id: sourceVolumeProc
    property var callback
    command: ["pactl", "get-source-volume", "@DEFAULT_SOURCE@"]
    stdout: StdioCollector {
      onStreamFinished: {
        const m = text.match(/(\d+)%/)
        if (sourceVolumeProc.callback)
          sourceVolumeProc.callback(m ? parseInt(m[1], 10) : 50)
      }
    }
  }

  Process {
    id: sourceMuteProc
    property var callback
    command: ["pactl", "get-source-mute", "@DEFAULT_SOURCE@"]
    stdout: StdioCollector {
      onStreamFinished: {
        const muted = /yes/i.test(text)
        if (sourceMuteProc.callback)
          sourceMuteProc.callback(muted)
      }
    }
  }

  Process {
    id: defaultSourceProc
    property var callback
    command: ["pactl", "get-default-source"]
    stdout: StdioCollector {
      onStreamFinished: {
        if (defaultSourceProc.callback)
          defaultSourceProc.callback(text.trim())
      }
    }
  }

  Process {
    id: sourcesProc
    property var callback
    property string defaultName: ""
    command: ["pactl", "list", "short", "sources"]
    stdout: StdioCollector {
      onStreamFinished: {
        const def = sourcesProc.defaultName
        const lines = text.trim().split("\n").filter(l => l.length)
        const out = []
        for (let i = 0; i < lines.length; i++) {
          const parts = lines[i].split("\t")
          if (parts.length < 2)
            continue
          const name = parts[1]
          // Skip monitor-of-sink pseudo sources
          if (name.indexOf(".monitor") >= 0)
            continue
          out.push({
            id: parts[0],
            name: name,
            label: root.formatAudioDeviceName(name),
            driver: parts[2] || "",
            sample: parts[3] || "",
            state: parts[4] || "",
            isDefault: name === def
          })
        }
        if (sourcesProc.callback)
          sourcesProc.callback(out)
      }
    }
  }

  Process {
    id: generalWriteProc
    command: ["true"]
  }

  Process {
    id: monitorsWriteProc
    command: ["true"]
  }

  Process {
    id: pkgResolveProc
    command: ["true"]
    stdout: StdioCollector {
      onStreamFinished: {
        const bin = text.trim()
        if (!bin.length) {
          // Dogfood without install: fall back to terminal + sudo
          const a = root.pkgPendingAction
          const p = root.pkgPendingPkg
          root.packageOpBusy = false
          root.packageOpStatus = "proteus-pkg missing — opened terminal"
          root.pkgPendingAction = ""
          root.pkgPendingPkg = ""
          if (a === "sync")
            root.openPacmanTerminal(["sudo", "pacman", "-Sy"])
          else if (a === "upgrade")
            root.openPacmanTerminal(["sudo", "pacman", "-Syu"])
          else if (a === "install" && p.length)
            root.openPacmanTerminal(["sudo", "pacman", "-S", p])
          root.packageOpFinished(false, "proteus-pkg not installed; used terminal fallback")
          return
        }
        root._startPkgMutator(bin)
      }
    }
  }

  Process {
    id: pkgMutatorProc
    command: ["true"]

    stdout: StdioCollector {
      id: pkgOut
    }
    stderr: StdioCollector {
      id: pkgErr
    }
    onExited: (exitCode, exitStatus) => {
      const out = pkgOut.text.trim()
      const err = pkgErr.text.trim()
      if (exitCode === 0) {
        const last = out.split("\n").filter(l => l.length).pop() || "Done."
        root._finishPkgMutator(true, last)
        return
      }
      if (exitCode === 126 || exitCode === 127) {
        root._finishPkgMutator(false, err || "Authentication cancelled or helper missing.")
        return
      }
      const msg = (err || out).split("\n").filter(l => l.length).pop() || ("Failed (exit " + exitCode + ")")
      root._finishPkgMutator(false, msg)
    }
  }

  Component.onCompleted: {
    applyHyprland()
    applyAudioLatency()
    Hardware.refresh()
  }
}
