// Chrome tokens — single source for the env/chrome/ sibling export.
//
// These constants mirror the frame tokens in shell/shared/Theme.qml (spec:
// docs/proteus/CHROME.md). The generators render env/chrome/chrome-tokens.json
// and chrome-tokens.css byte-for-byte; golden tests below pin the repo
// artifacts to this module, flipping the export from hand-maintained mirror to
// generated artifact (OWNED-STACK rung 0, slice 1). Accent stays Config-driven
// at runtime — the export carries defaults for sibling binding only.

pub const SPACE: [(&str, u32); 5] = [
    ("spaceXs", 4),
    ("spaceSm", 8),
    ("spaceMd", 12),
    ("spaceLg", 16),
    ("spaceXl", 24),
];

pub const RADIUS: [(&str, u32); 6] = [
    ("radiusSm", 6),
    ("radius", 8),
    ("radiusMd", 10),
    ("radiusLg", 12),
    ("radiusXl", 16),
    ("radiusPill", 22),
];

pub const DANGER: &str = "#ff453a";
pub const ACCENT_DEFAULT: &str = "#3d8bfd";

pub struct ModeSurfaces {
    pub bg: &'static str,
    pub bg_panel: &'static str,
    pub bg_elevated: &'static str,
    pub bg_hover: &'static str,
    pub border: &'static str,
    pub separator: &'static str,
    pub text: &'static str,
    pub text_dim: &'static str,
    pub text_mute: &'static str,
}

pub const LIGHT: ModeSurfaces = ModeSurfaces {
    bg: "#f2f2f7",
    bg_panel: "#e8e8ed",
    bg_elevated: "#ffffff",
    bg_hover: "#e5e5ea",
    border: "#d1d1d6",
    separator: "rgba(61, 61, 66, 0.29)",
    text: "#1c1c1e",
    text_dim: "#636366",
    text_mute: "#8e8e93",
};

pub const DARK: ModeSurfaces = ModeSurfaces {
    bg: "#000000",
    bg_panel: "#1c1c1e",
    bg_elevated: "#1c1c1e",
    bg_hover: "#2c2c2e",
    border: "#2c2c2e",
    separator: "rgba(255, 255, 255, 0.1)",
    text: "#f5f5f7",
    text_dim: "#98989d",
    text_mute: "#636366",
};

fn mode_json(m: &ModeSurfaces, indent: &str) -> String {
    format!(
        "{i}\"bg\": \"{}\",\n{i}\"bgPanel\": \"{}\",\n{i}\"bgElevated\": \"{}\",\n\
         {i}\"bgHover\": \"{}\",\n{i}\"border\": \"{}\",\n{i}\"separator\": \"{}\",\n\
         {i}\"text\": \"{}\",\n{i}\"textDim\": \"{}\",\n{i}\"textMute\": \"{}\"",
        m.bg,
        m.bg_panel,
        m.bg_elevated,
        m.bg_hover,
        m.border,
        m.separator,
        m.text,
        m.text_dim,
        m.text_mute,
        i = indent
    )
}

/// env/chrome/chrome-tokens.json — exact bytes.
pub fn render_json() -> String {
    let space = SPACE
        .iter()
        .map(|(k, v)| format!("    \"{k}\": {v}"))
        .collect::<Vec<_>>()
        .join(",\n");
    let radius = RADIUS
        .iter()
        .map(|(k, v)| format!("    \"{k}\": {v}"))
        .collect::<Vec<_>>()
        .join(",\n");
    format!(
        "{{\n  \"schema\": \"proteus-chrome-tokens/v1\",\n  \"source\": \"docs/proteus/CHROME.md + shell/shared/Theme.qml\",\n  \"note\": \"Frame tokens only (chrome \u{2260} canvas). accent is Config-driven at runtime; export lists defaults for sibling binding.\",\n  \"space\": {{\n{space}\n  }},\n  \"radius\": {{\n{radius}\n  }},\n  \"danger\": \"{DANGER}\",\n  \"accentDefault\": \"{ACCENT_DEFAULT}\",\n  \"modes\": {{\n    \"light\": {{\n{light}\n    }},\n    \"dark\": {{\n{dark}\n    }}\n  }}\n}}\n",
        light = mode_json(&LIGHT, "      "),
        dark = mode_json(&DARK, "      "),
    )
}

fn mode_css(m: &ModeSurfaces) -> String {
    [
        ("bg", m.bg),
        ("bg-panel", m.bg_panel),
        ("bg-elevated", m.bg_elevated),
        ("bg-hover", m.bg_hover),
        ("border", m.border),
        ("separator", m.separator),
        ("text", m.text),
        ("text-dim", m.text_dim),
        ("text-mute", m.text_mute),
    ]
    .iter()
    .map(|(k, v)| format!("  --proteus-{k}: {v};\n"))
    .collect()
}

/// env/chrome/chrome-tokens.css — exact bytes.
pub fn render_css() -> String {
    let mut css = String::new();
    css.push_str(
        "/**\n * Proteus chrome tokens \u{2014} sibling CSS bridge (frame only; chrome \u{2260} canvas).\n * Spec: docs/proteus/CHROME.md \u{00b7} live: shell/shared/Theme.qml\n * Generated by services/proteus-shell-core (tokens --css) to match chrome-tokens.json.\n */\n\n",
    );
    css.push_str(":root,\n[data-proteus-chrome=\"light\"] {\n");
    css.push_str(&mode_css(&LIGHT));
    css.push_str(&format!(
        "  --proteus-danger: {DANGER};\n  --proteus-accent: {ACCENT_DEFAULT};\n"
    ));
    for (k, v) in SPACE {
        let kebab = k
            .strip_prefix("space")
            .map(|s| format!("space-{}", s.to_lowercase()))
            .unwrap();
        css.push_str(&format!("  --proteus-{kebab}: {v}px;\n"));
    }
    for (k, v) in RADIUS {
        let kebab = match k.strip_prefix("radius") {
            Some("") => "radius".to_string(),
            Some(s) => format!("radius-{}", s.to_lowercase()),
            None => unreachable!(),
        };
        css.push_str(&format!("  --proteus-{kebab}: {v}px;\n"));
    }
    css.push_str("}\n\n[data-proteus-chrome=\"dark\"] {\n");
    css.push_str(&mode_css(&DARK));
    css.push_str("}\n");
    css
}

#[cfg(test)]
mod tests {
    use super::*;

    // Golden pins: the repo artifacts are generated from this module. When
    // tokens change, regenerate with `proteus-shell-core tokens --write` (or
    // --json/--css to stdout) and sync the Tauri sibling vendored copies.
    const REPO_JSON: &str = include_str!("../../../env/chrome/chrome-tokens.json");
    const REPO_CSS: &str = include_str!("../../../env/chrome/chrome-tokens.css");

    #[test]
    fn json_matches_repo_artifact() {
        assert_eq!(render_json(), REPO_JSON);
    }

    #[test]
    fn css_matches_repo_artifact() {
        assert_eq!(render_css(), REPO_CSS);
    }

    #[test]
    fn json_is_valid_and_shaped() {
        let v: serde_json::Value = serde_json::from_str(&render_json()).unwrap();
        assert_eq!(v["schema"], "proteus-chrome-tokens/v1");
        for key in ["spaceXs", "spaceSm", "spaceMd", "spaceLg", "spaceXl"] {
            assert!(v["space"][key].is_u64(), "{key}");
        }
        for mode in ["light", "dark"] {
            for key in ["bg", "bgPanel", "text", "separator"] {
                assert!(v["modes"][mode][key].is_string(), "{mode}.{key}");
            }
        }
    }

    #[test]
    fn css_carries_required_vars() {
        let css = render_css();
        for needle in [
            "--proteus-bg:",
            "--proteus-bg-panel:",
            "--proteus-text:",
            "--proteus-space-md: 12px",
            "--proteus-radius: 8px",
            "--proteus-radius-pill: 22px",
            "--proteus-danger:",
            "data-proteus-chrome=\"dark\"",
        ] {
            assert!(css.contains(needle), "{needle}");
        }
    }
}
