pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick
import ".."

// Proteus display control — monitor rule generation, live apply via hyprctl,
// and the ~/.config/hypr/proteus-monitors.conf fragment.
//
// Extracted from Config.qml. Behaviour only: this owns proteus-monitors.conf,
// which is a separate file from settings.json (still solely Config's).
Singleton {
  id: root

  readonly property string monitorsConfPath: Quickshell.env("HOME") + "/.config/hypr/proteus-monitors.conf"

  // Identify flash target (PanelWindow in Settings shell.qml)
  property string identifyTarget: ""
  property bool identifyActive: false

  function monitorRule(m) {
    const name = m.name || "?"
    const w = Math.round(m.width || 1920)
    const h = Math.round(m.height || 1080)
    const hz = Math.round(m.refreshRate || m.refresh || 60)
    const x = Math.round(m.x || 0)
    const y = Math.round(m.y || 0)
    const scale = Number(m.scale)
    const scaleStr = isFinite(scale) && scale > 0 ? String(Math.round(scale * 100) / 100) : "1"
    let t = Math.round(Number(m.transform))
    if (!isFinite(t) || t < 0)
      t = 0
    t = t % 8
    // Always emit transform so re-apply is deterministic
    return name + "," + w + "x" + h + "@" + hz + "," + x + "x" + y + "," + scaleStr + ",transform," + t
  }

  function monitorsConfText(monitors, live) {
    let body = "# Generated by Proteus Settings — Displays\n"
    if (live) {
      body += "# Applied from Settings → Displays (scale / mode / orientation). Edit here or re-apply in Settings.\n"
    } else {
      body += "# Inspect / edit manually. Apply in Settings → Displays to write live monitor lines.\n"
    }
    body += "# Sourced by Hyprland when present in hyprland.conf.\n\n"
    const list = monitors || []
    for (let i = 0; i < list.length; i++) {
      const m = list[i]
      const name = m.name || "?"
      body += "# " + name + (m.focused ? " (active)" : "") + "\n"
      const rule = monitorRule(m)
      if (live)
        body += "monitor = " + rule + "\n\n"
      else
        body += "# monitor = " + rule + "\n\n"
    }
    if (!list.length)
      body += "# No monitors detected yet.\n# monitor = ,preferred,auto,1\n"
    return body
  }

  function _writeMonitorsConf(body) {
    const confHex = Config.utf8Hex(body)
    monitorsWriteProc.command = ["python3", "-c",
      "import os, pathlib\n"
      + "home = pathlib.Path(os.environ['HOME'])\n"
      + "(home / '.config/hypr').mkdir(parents=True, exist_ok=True)\n"
      + "path = home / '.config/hypr/proteus-monitors.conf'\n"
      + "new = bytes.fromhex('" + confHex + "').decode()\n"
      + "marker = '# Generated by Proteus Settings — Displays'\n"
      + "existing = path.read_text(encoding='utf-8') if path.is_file() else ''\n"
      + "if (not path.is_file()) or (len(existing.strip()) == 0) or existing.startswith(marker):\n"
      + "    path.write_text(new, encoding='utf-8')\n"
      + "hypr = home / '.config/hypr/hyprland.conf'\n"
      + "if hypr.is_file():\n"
      + "    text = hypr.read_text(encoding='utf-8')\n"
      + "    if 'proteus-monitors.conf' not in text:\n"
      + "        hypr.write_text(text.rstrip() + '\\n\\n# Proteus displays (Settings → Displays)\\nsource = ~/.config/hypr/proteus-monitors.conf\\n', encoding='utf-8')\n"
      + "print('ok')\n"
    ]
    monitorsWriteProc.running = false
    monitorsWriteProc.running = true
  }

  // First-run seed only — never overwrite an existing Proteus-managed conf on refresh.
  function ensureMonitorsConfStub(monitors) {
    const list = monitors || []
    const body = monitorsConfText(list, false)
    const confHex = Config.utf8Hex(body)
    monitorsWriteProc.command = ["python3", "-c",
      "import os, pathlib\n"
      + "home = pathlib.Path(os.environ['HOME'])\n"
      + "(home / '.config/hypr').mkdir(parents=True, exist_ok=True)\n"
      + "path = home / '.config/hypr/proteus-monitors.conf'\n"
      + "new = bytes.fromhex('" + confHex + "').decode()\n"
      + "if not path.is_file():\n"
      + "    path.write_text(new, encoding='utf-8')\n"
      + "hypr = home / '.config/hypr/hyprland.conf'\n"
      + "if hypr.is_file():\n"
      + "    text = hypr.read_text(encoding='utf-8')\n"
      + "    if 'proteus-monitors.conf' not in text:\n"
      + "        hypr.write_text(text.rstrip() + '\\n\\n# Proteus displays (Settings → Displays)\\nsource = ~/.config/hypr/proteus-monitors.conf\\n', encoding='utf-8')\n"
      + "print('ok')\n"
    ]
    monitorsWriteProc.running = false
    monitorsWriteProc.running = true
  }

  function persistMonitorsConf(monitors) {
    _writeMonitorsConf(monitorsConfText(monitors || [], true))
  }

  // Live apply one monitor; `allMonitors` is the full set to persist (with this monitor updated).
  function applyMonitor(spec, allMonitors) {
    if (!spec || !spec.name)
      return
    applyMonitorRule(monitorRule(spec), allMonitors)
  }

  function applyMonitorRule(rule, allMonitors) {
    if (!rule || !String(rule).length)
      return
    // execDetached is more reliable from Settings than a reused Singleton Process
    Quickshell.execDetached({
      command: ["hyprctl", "keyword", "monitor", String(rule)]
    })
    if (allMonitors && allMonitors.length)
      persistMonitorsConf(allMonitors)
  }

  function identifyMonitor(name) {
    if (!name || !String(name).length)
      return
    const n = String(name)
    identifyTarget = n
    identifyActive = false
    identifyActive = true
    identifyClearTimer.restart()
    Quickshell.execDetached({
      command: ["hyprctl", "dispatch", "focusmonitor", n]
    })
    Quickshell.execDetached({
      command: ["hyprctl", "notify", "1", "1800", "0", "Monitor: " + n]
    })
  }

  function openMonitorsConfInEditor() {
    Quickshell.execDetached({
      command: ["bash", "-lc", "mkdir -p \"$HOME/.config/hypr\"; touch \"$HOME/.config/hypr/proteus-monitors.conf\"; (command -v xdg-open >/dev/null && xdg-open \"$HOME/.config/hypr/proteus-monitors.conf\") || exec foot -e nvim \"$HOME/.config/hypr/proteus-monitors.conf\""]
    })
  }

  Timer {
    id: identifyClearTimer
    interval: 1700
    repeat: false
    onTriggered: {
      root.identifyActive = false
      root.identifyTarget = ""
    }
  }

  Process {
    id: monitorsWriteProc
    command: ["true"]
  }
}
